/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfaceOn.java
 *
 * Created on 23/05/2011, 15:21:58
 */

package visaodesktop;
import Util.Util;
import sistema_correio.*;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author usuario
 */
public class InterfaceOn extends javax.swing.JFrame {

    /** Creates new form InterfaceOn */
    //JTabbedPane tab = new JTabbedPane();
    public static JPanel mainbox = new MainboxInterface();
    public JPanel trash = new TrashInterface();
    public JPanel send = new SendInterface();
    public JTabbedPane painel2 = new javax.swing.JTabbedPane();
    ImageIcon msgIcon = new ImageIcon("c:/Icons/mainbox.png");
    ImageIcon trashIcon = new ImageIcon("c:/Icons/trash.png");
    ImageIcon viewFoldersIcon = new ImageIcon("c:/Icons/folders.png");
    ImageIcon newMessageIcon = new ImageIcon("c:/Icons/newmessage.png");
    ImageIcon logoutIcon = new ImageIcon("c:/Icons/logout.png");

    public InterfaceOn() {
        initComponents();
        this.setTitle("Sistema de correio");
        //this.setSize(450, 400);
        this.setResizable(false);
        painel1.addTab("Caixa de Entrada", msgIcon,mainbox);
        painel1.addTab("Lixeira", trashIcon,trash);
        //this.add(painel1, BorderLayout.CENTER);
        //tab.add("Caixa de Entrada", mainbox);
        //tab.add("Enviar", send);
        //this.add(tab, BorderLayout.CENTER);
        this.setLocationRelativeTo(null);
        bemvindo.setText("Seja bem-vindo(a) " + Main.interfaceoff.getServer().getOnline().getUser().getName() + ".");
        date.setText("Hoje é " + Util.getDay() + ".");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel1 = new javax.swing.JTabbedPane();
        bemvindo = new javax.swing.JLabel();
        view = new javax.swing.JButton(viewFoldersIcon);
        button_send = new javax.swing.JButton(newMessageIcon);
        logout = new javax.swing.JButton(logoutIcon);
        date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                painel1StateChanged(evt);
            }
        });

        bemvindo.setText("jLabel1");

        view.setText("Ver Pastas");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        button_send.setText("Nova Mensagem");
        button_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sendActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        date.setText("jLabel1");

        jLabel1.setText("Desenvolvido por: Alexandre Silvestre Ferreira e Gilson Vinicius Guimarães");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_send)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bemvindo)
                    .addComponent(date)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bemvindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_send, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        painel1.removeAll();
        painel1.addTab("Caixa de Entrada", msgIcon,mainbox);
        painel1.addTab("Lixeira", trashIcon,trash);
    }//GEN-LAST:event_viewActionPerformed

    private void button_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sendActionPerformed
        // TODO add your handling code here:
        painel1.removeAll();
        send = new SendInterface();
        painel1.add("Enviar", send);
    }//GEN-LAST:event_button_sendActionPerformed

    private void painel1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_painel1StateChanged

        mainbox = new MainboxInterface();
        trash = new TrashInterface();
    }//GEN-LAST:event_painel1StateChanged

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(logout, "Realmente deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0)
        {
            Main.interfaceoff.getServer().setOnline(null);
            Main.interfaceoff.interfaceon.setVisible(false);
            Main.interfaceoff.setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceOn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bemvindo;
    private javax.swing.JButton button_send;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JTabbedPane painel1;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables

}
