/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TrashInterface.java
 *
 * Created on 23/05/2011, 21:56:19
 */

package visaodesktop;
import java.util.List;
import javax.swing.JOptionPane;
import sistema_correio.Main;
import sistema_correio.Message;

/**
 *
 * @author Gilson
 */
public class TrashInterface extends javax.swing.JPanel {

    private MessageInterface message;

    /** Creates new form TrashInterface */
    public TrashInterface() {
        initComponents();
        this.setVisible(true);
        messages.setEditable(false);
        refreshTrash();
    }

    public void refreshTrash() {
        String inbox = "";
        messages.setText("");
        ids.removeAllItems();
        for (int i = 0; i < Main.interfaceoff.getServer().getOnline().getTrash().size(); i++) {
            inbox  +=  (i+1 + ") " + Main.interfaceoff.getServer().getOnline().getTrash().get(i).getTitle() + "\n");
            ids.addItem("Mensagem " + (i+1));
        }
        messages.setCaretPosition(0);
        messages.setText(inbox);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        messages = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        ids = new javax.swing.JComboBox();
        read = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        messages.setColumns(20);
        messages.setRows(5);
        messages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                messagesMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(messages);

        jLabel1.setText("Id - Remetente -  Assunto - Data - Status ");

        delete.setText("Excluir");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        ids.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsActionPerformed(evt);
            }
        });

        read.setText("Ler");
        read.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readMouseClicked(evt);
            }
        });

        jLabel2.setText("Selecione o id da mensagem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ids, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(read)
                                .addGap(18, 18, 18)
                                .addComponent(delete)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(read)
                    .addComponent(delete))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if (ids.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Sua lixeira está vazia");
        } else {
            if (JOptionPane.showConfirmDialog(null, "Confirmar exclusão da mensagem?\nA mensagem será excluida permanentemente!", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0)
                Main.interfaceoff.getServer().getOnline().deleteMessage(ids.getSelectedIndex());
        }
        refreshTrash();
}//GEN-LAST:event_deleteActionPerformed

    private void readMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readMouseClicked
        if (ids.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(this, "Sua lixeira está vazia");
        else {
            message = new MessageInterface(Main.interfaceoff.getServer().getOnline().getTrash().get(ids.getSelectedIndex()));
            Main.interfaceoff.getServer().getOnline().getTrash().get(ids.getSelectedIndex()).setRead();
            message.setVisible(true);
        }
        refreshTrash();
}//GEN-LAST:event_readMouseClicked

    private void idsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idsActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        refreshTrash();
    }//GEN-LAST:event_formFocusGained

    private void messagesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagesMouseEntered
        // TODO add your handling code here:
        refreshTrash();
    }//GEN-LAST:event_messagesMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JComboBox ids;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messages;
    private javax.swing.JButton read;
    // End of variables declaration//GEN-END:variables

}
